package metrics

// OptionalTSVColumns are elite QA expvar columns (default 0 when absent from header).
var OptionalTSVColumns = []string{
	"order_fail_create",
	"order_fail_amend",
	"order_fail_cancel",
	"order_fail_ret_10003",
	"order_fail_ret_10006",
	"order_fail_ret_10001",
	"order_fail_ret_10016",
	"order_fail_ret_110001",
	"order_fail_ret_110007",
	"order_fail_ret_110013",
	"order_fail_ret_110021",
	"order_fail_ret_110090",
	"order_fail_ret_110094",
	"order_fail_ret_110059",
	"order_fail_ret_110123",
	"order_fail_ret_110126",
	"algo_stopped_permanent",
	"risk_limit_margin_reduced",
	"tp_missing_create_ok",
	"tp_missing_create_fail",
	"tp_missing_close_position",
	"sl_setup_started",
	"sl_setup_ok",
	"sl_setup_fail",
	"sl_setup_cancelled",
	"sl_price_past_immediate_close",
	"partial_tp_needs_cancel",
	"position_reset_liquidation",
	"position_reset_manual",
	"price_wake_signals",
	"price_exec_runs",
	"private_order_wake_signals",
	"private_order_events_signaled",
	"private_order_drain_batches",
	"private_order_events_drained",
}
